// <auto-generated />
using System;
using EventsItAcademyGe.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsItAcademyGe.Persistence.Migrations
{
    [DbContext(typeof(EventsItAcademyGeDbContext))]
    [Migration("20230312073620_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsItAcademyGe.Domain.Models.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID");

                    b.ToTable("Statusses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StatusCode = 1,
                            StatusMessage = "Active"
                        },
                        new
                        {
                            ID = 2,
                            StatusCode = 2,
                            StatusMessage = "Deleted"
                        });
                });

            modelBuilder.Entity("EventsItAcademyGe.Domain.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("Status");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventsItAcademyGe.Domain.Models.User", b =>
                {
                    b.HasOne("EventsItAcademyGe.Domain.Models.Status", null)
                        .WithMany("UsersWithThisStatusCode")
                        .HasForeignKey("Status")
                        .HasPrincipalKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventsItAcademyGe.Domain.Models.Status", b =>
                {
                    b.Navigation("UsersWithThisStatusCode");
                });
#pragma warning restore 612, 618
        }
    }
}
